apiVersion: v1
kind: Secret
metadata:
  name: {{ include "backend.fullname" . }}-secrets
  labels:
    app: {{ include "backend.name" . }}
type: Opaque
stringData:
  DB_USER: {{ .Values.secrets.DB_USER | quote }}
  DB_PASSWORD: {{ .Values.secrets.DB_PASSWORD | quote }}
  SLACK_BOT_TOKEN: {{ .Values.secrets.SLACK_BOT_TOKEN | quote }}
  SLACK_CHANNEL_ID: {{ .Values.secrets.SLACK_CHANNEL_ID | quote }}